Martin molinero/develop
wizeline/react-crash-course-2021 pull request #1
Opened 2021-02-09 04:33 UTC by MartinMolinero

2021-02-09 04:40 UTC, MartinMolinero commented
Since I was in PTO all the previous week, I just started working on this.
So far I have:
- [x] Working version of the app
- [x] Naive testing on simple components (Missing components that interact with redux)
- [ ] SSR

2021-02-18 21:28 UTC, dianasaurio commented on src/components/App/App.test.jsx
> +import { render, screen } from '@testing-library/react';
How could you test this using enzyme?

2021-02-18 22:03 UTC, dianasaurio requested changes

2021-02-18 22:03 UTC, dianasaurio commented on src/components/Menu/Menu.test.jsx
> +configure({adapter: new Adapter()});
You can create a setupTest.js file where you configure the enzyme adapter so you don't repeat the code in every test: 
https://create-react-app.dev/docs/running-tests/#initializing-test-environment

2021-02-18 22:03 UTC, dianasaurio commented on src/utils/test-utils.js
> +import { render as rtlRender } from '@testing-library/react'
Using enzyme, you don't need react testing library. Enzyme comes with methods to mount and shallow render a component: 
https://enzymejs.github.io/enzyme/docs/api/shallow.html

2021-02-18 22:03 UTC, dianasaurio commented on src/components/Private/Private.component.jsx
> +  mapDispatchToProps,
If your mapDispatchToProps doesn't do anything, you can omit it or just pass a null

2021-02-18 22:03 UTC, dianasaurio commented on src/components/Searchbar/Searchbar.component.jsx
> +  return state
I see that you are connecting the component with the whole redux state but you aren't using it, if you are not using it, you can just pass the necessary values, in this case, the video search

2021-02-18 22:03 UTC, dianasaurio commented on src/components/VideoItem/VideoItem.test.jsx
> +import userEvent from '@testing-library/user-event';
Use enzyme capabilities like simulate function instead

2021-02-18 22:03 UTC, dianasaurio commented on src/pages/Explore/Explore.page.jsx
> +  return state
If you are only connecting this component to prop drill to VideoList, I suggest VideoList be connected to the redux state instead, so you avoid unnecessary rendering for both components.

2021-02-18 22:03 UTC, dianasaurio commented on src/pages/Home/Home.page.authenticated.test.jsx
> +      <Provider store={store}>
Another way to test components using redux is to export the component without the connect HOC, so when you shallow render it in your tests, you can just pass the needed props.

2021-02-18 22:03 UTC, dianasaurio commented on src/pages/VideoDetail/VideoDetail.page.test.jsx
> +//         },
Remove unused code

2021-02-18 22:03 UTC, dianasaurio commented on src/redux/reducers/videosReducer.js
> +import { storage } from '../../utils/storage';
What does storages does? I don't understand why you call storage.set('videos', JSON.stringify(something)); on every case for the reducer

2023-07-03 19:18 UTC, closed without merging